### ISSUE TITLE
please update cart and checkout page

### ISSUE THREAD

**Issue by bikash02** [cleonixtechnologies/Tyre-Battery#3]
http://cleonetlive.info/projects/tyreandbattery/wp/cart/

**Comment by i-puspita** [comment]
Add to cart button is not working so, cannot check the cart page after adding product

**Comment by i-puspita** [comment]
updated

**Comment by bikash02** [comment]
@i-puspita  please format the checkout page

**Comment by i-puspita** [comment]
updated
